# Generated by Django 5.1.3 on 2024-11-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=255, unique=True, verbose_name='Путь к файлу')),
                ('size', models.PositiveIntegerField(verbose_name='Размер файла (Кб)')),
            ],
            options={
                'verbose_name': 'Документы пользователя',
                'verbose_name_plural': 'Документы пользователей',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_type', models.CharField(max_length=10, unique=True, verbose_name='Тип файла')),
                ('price', models.FloatField(verbose_name='Цена за 1 Кб')),
            ],
            options={
                'verbose_name': 'Цена услуги',
                'verbose_name_plural': 'Цены услуг',
            },
        ),
    ]
