# Generated by Django 5.1.3 on 2024-11-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_analyze', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docs',
            options={'verbose_name': 'Документ пользователя', 'verbose_name_plural': 'Документы пользователей'},
        ),
        migrations.AddField(
            model_name='docs',
            name='fastapi_document_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID документа от FastAPI'),
        ),
    ]
